name: TypeScript Agent Action
description: GitHub Action for TypeScript analysis and PR file detection
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  apiKey:
    description: API key for authenticating with the backend service
    required: true
    default: ''
  test-structure:
    description: Test file structure (siblingFolder or rootFolder)
    required: false
    default: 'siblingFolder'
  test-framework:
    description: Test framework to use (jest, mocha, or vitest)
    required: false
    default: 'jest'
  test-suffix:
    description: Test file suffix (spec or test)
    required: false
    default: 'spec'
  test-file-name:
    description: Test file naming convention (camelCase or kebabCase)
    required: false
    default: 'camelCase'
  calculate-coverage:
    description: Whether to calculate coverage (on or off)
    required: false
    default: 'on'
  coverage-threshold:
    description: Coverage threshold percentage (0-100)
    required: false
    default: '0'
  scout-concurrency:
    description: Number of concurrent scout processes (1-50)
    required: false
    default: '5'
  base-url:
    description: Base URL for the API endpoint
    required: false
    default: 'https://api.startearly.ai'
  token:
    description:
      GitHub token for accessing PR information (defaults to GITHUB_TOKEN)
    required: false
    default: ''

# Define your outputs here.
outputs:
  pre-coverage:
    description: Coverage data before analysis
  post-coverage:
    description: Coverage data after analysis

runs:
  using: node20
  main: dist/index.js
