name: Conventional Commit
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled


jobs:
  check-pr-title:
    uses: earlyai/gha-workflows/.github/workflows/conventional-commit.yml@master
    secrets:
      gha-workflows-read-pat: ${{ secrets.GHA_WORKFLOWS_READ_PAT }}
