name: Release-Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

  build-and-publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ needs.release-please.outputs.tag }}

      - name: Authenticate npm
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@earlyai:registry=https://npm.pkg.github.com" >> ~/.npmrc
  
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: Build
        run: |
          npm ci
          npm run build

      - name: Commit only dist/** and action.yml
        uses: EndBug/add-and-commit@v9
        with:
          remove: |
            . ':(exclude)dist' ':(exclude)action.yml'
          add: |
            dist/**
            action.yml
          message: "Release artifacts for ${{ needs.release-please.outputs.tag }}"
          push: false
          default_author: github_actions
        
      - name: Move release tag to minimal commit
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ needs.release-please.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        # 3) OPTIONAL: also move vX and vX.Y moving tags
      - name: Move major/minor tags to same commit
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{ needs.release-please.outputs.major }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Move minor tag
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}