name: Release-Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      tag: ${{ steps.release.outputs.tag_name }}
      sha: ${{ steps.release.outputs.sha }}
      prs_created: ${{ steps.release.outputs.prs_created }}
      pr: ${{ steps.release.outputs.pr }}
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          

  build-release-pr:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.prs_created }} && ! ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
      packages: read
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ fromJson(needs.release-please.outputs.pr).headBranchName }}

      - name: Authenticate npm
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@earlyai:registry=https://npm.pkg.github.com" >> ~/.npmrc
  
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: Build
        run: |
          npm ci
          npm run build

      - name: Commit built files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "build: update dist for release"
          branch: ${{ fromJson(needs.release-please.outputs.pr).head.ref }}
          file_pattern: |
            dist/**

      - name: Tag QA
        uses: richardsimko/update-tag@v1
        with:
          tag_name: QA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  retag-release:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ needs.release-please.outputs.tag }}
          
      - name: Tag major version
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{ needs.release-please.outputs.major }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag minor version
        uses: richardsimko/update-tag@v1
        with:
          tag_name: v${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag QA
        uses: richardsimko/update-tag@v1
        with:
          tag_name: QA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}